### ISSUE TITLE
initial black screen on android

### ISSUE THREAD

**Issue by revolunet** [shprink/wordpress-hybrid-client#13] opened 2015-05-25 21:21 UTC
On android 5, we get a black screen after the splash screen. maybe delay it until the view is fully rendered ?

**Comment by shprink** [comment] 2015-05-25 21:25
I have it too, thanks for letting me know.

**Comment by abedalzain** [comment] 2015-05-25 21:26
I did not have it yet, but maybe you have to add :
cordova plugin add cordova-plugin-whitelist

**Comment by shprink** [comment] 2015-07-14 06:12
Closing cannot reproduce anymore

**Closed by shprink** 2015-07-14 06:12 UTC
Labels: enhancement
